version: '3'

services:
  ssh-jump:
    container_name: ssh-jump
    build: docker/
    image: neogenia/ssh-jump
    tty: true
    ports:
      - ${SSHD_PORT:-5432}:22
    environment:
      CONTAINER_NAME: ssh-jump-$HOSTNAME
      LOGIN_ALERT_MAIL_TO:
      NOTIFY_WEBHOOK_URL:
