# an additional docker-compose file for add ezgate container
#   by w.maeda@neogenia.co.jp (2021-04-16)

version: '3.5'
services:
 ezgate:
  image: neogenia/ez-gate:20240610
  volumes:
    - ./ezgate_mnt:/mnt/
  environment:
    TZ: Asia/Tokyo
    CONFIG_PATH: /mnt/config.rb
    CERT_EMAIL: neogenia.dev@gmail.com
    DEBUG: 1
  ports:
    - 80:80
    - 443:443
  networks:
   zbx_net_frontend:
    aliases:
     - ez-gate

