# Define an access log for VirtualHosts that don't define their own logfile
# CustomLog ${APACHE_LOG_DIR}/other_vhosts_access.log vhost_combined
CustomLog "|/usr/bin/rotatelogs -l -n 60 /var/log/apache2/other_vhosts_access.log 86400" vhost_combined